#!/bin/bash

sed -i "s/FIREBASE_API_KEY_PLACEHOLDER/$FIREBASE_API_KEY/g" env.js
sed -i "s/FIREBASE_AUTH_DOMAIN_PLACEHOLDER/$FIREBASE_AUTH_DOMAIN/g" env.js  
sed -i "s/FIREBASE_DATABASE_URL_PLACEHOLDER/${FIREBASE_DATABASE_URL//\//\\/}/g" env.js
sed -i "s/FIREBASE_PROJECT_ID_PLACEHOLDER/$FIREBASE_PROJECT_ID/g" env.js
sed -i "s/FIREBASE_STORAGE_BUCKET_PLACEHOLDER/$FIREBASE_STORAGE_BUCKET/g" env.js
sed -i "s/FIREBASE_MESSAGING_SENDER_ID_PLACEHOLDER/$FIREBASE_MESSAGING_SENDER_ID/g" env.js
sed -i "s/FIREBASE_APP_ID_PLACEHOLDER/$FIREBASE_APP_ID/g" env.js
sed -i "s/GEMINI_API_URL_PLACEHOLDER/${GEMINI_API_URL//\//\\/}/g" env.js
sed -i "s/FORMSPREE_URL_PLACEHOLDER/${FORMSPREE_URL//\//\\/}/g" env.js

echo "Environment variables replaced in env.js"