window.env = {
  FIREBASE_API_KEY: "FIREBASE_API_KEY_PLACEHOLDER",
  FIREBASE_AUTH_DOMAIN: "FIREBASE_AUTH_DOMAIN_PLACEHOLDER",
  FIREBASE_DATABASE_URL: "FIREBASE_DATABASE_URL_PLACEHOLDER", 
  FIREBASE_PROJECT_ID: "FIREBASE_PROJECT_ID_PLACEHOLDER",
  FIREBASE_STORAGE_BUCKET: "FIREBASE_STORAGE_BUCKET_PLACEHOLDER",
  FIREBASE_MESSAGING_SENDER_ID: "FIREBASE_MESSAGING_SENDER_ID_PLACEHOLDER",
  FIREBASE_APP_ID: "FIREBASE_APP_ID_PLACEHOLDER",
  GEMINI_API_URL: "GEMINI_API_URL_PLACEHOLDER",
  FORMSPREE_URL: "FORMSPREE_URL_PLACEHOLDER"
};